"""
Django settings for muxi_shop_api project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#把apps加入到项目根的搜索路径，导入的时候可以直接从源码包导入
sys.path.insert(0,BASE_DIR)
sys.path.insert(0,os.path.join(BASE_DIR,"apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9jal3=*t5n-!8^ns-w9&yw7j9s1g&niy+q!em-x=-wun129zrj"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cart",
    "comment",
    "goods",
    "menu",
    "order",
    "user",
    "address",
    "rest_framework",
    'corsheaders', #解决跨域问题的一个插件
]

CORS_ORIGIN_ALLOW_ALL=True
CORS_ALLOW_CREDENTIALS=True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "muxi_shop_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "muxi_shop_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         #"ENGINE": "django.db.backends.sqlite3",
#         #"NAME": BASE_DIR / "db.sqlite3",
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "muxi_shop",
#         "USER": "admin",
#         "PASSWORD": "123456",
#         "HOST": "192.168.1.119",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
#配置图片文件夹所在路径
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#静态文件服务器配置
#IMAGE_URL='http://localhost:8000/static/product_images/'

#DRF-JWT-TOKEN的全局身份验证配置
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES":["utils.jwt_auth.JwtHeaderAuthentication"]
}

#支付宝沙箱环境配置
APPID = "9021000158614658"	
ALI_PUB_KEY_PATH=os.path.join(BASE_DIR,"apps/pay/keys/alipay_key.txt")
PRIVATE_KEY_PATH=os.path.join(BASE_DIR,"apps/pay/keys/private_key.txt")
#异步接收url
#APP_NOTIFY_URL = "http://127.0.0.1:8000/alipay/notify"
#同步url 就是用户在页面上支付成功之后，然后就跳转的页面
#RETURN_URL="http://127.0.0.1:8000/alipay/return"
#是否是开发环境
ALIPAY_DEBUG=True

#做环境区分的代码
CURRENT_ENV = "dev"

if CURRENT_ENV == "dev":
    from .settings_dev import *
elif CURRENT_ENV == "test":
    from .settings_test import *
elif CURRENT_ENV == "prod":
    from .settings_prod import *